set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# Source the OpenSTLinux SDK environment before running CMake. The SDK exports
# CC/CXX and SDKTARGETSYSROOT. Override CROSS_COMPILE only when your SDK differs.
if(DEFINED ENV{CXX})
    set(CMAKE_CXX_COMPILER "$ENV{CXX}")
endif()

if(DEFINED ENV{SDKTARGETSYSROOT})
    set(CMAKE_SYSROOT "$ENV{SDKTARGETSYSROOT}")
    set(CMAKE_FIND_ROOT_PATH "$ENV{SDKTARGETSYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

